#!/bin/bash

# nombre del proyecto
PROJECT_DIR="/biometrical"

# nombre del entorno virtual
VENV_NAME="venv"

# directorio del proyecto
VENV_DIR="$PROJECT_DIR/$VENV_NAME"

# carpeta de scripts
SCRIPT_DIR="$PROJECT_DIR/src"

case "$1" in
start)
if [ ! -d "$VENV_DIR" ]; then
  echo "Virtual environment not found in $VENV_DIR. Please set up the virtual environment first."
    exit 1
fi

echo "Biometrial is starting..."
source "$VENV_DIR/bin/activate"
python "$SCRIPT_DIR/main.py" & echo "biometrical started with PID $!"
;;

stop)
echo "Stopping Biometrial..."
pkill -f "$SCRIPT_DIR/main.py"
echo "Biometrial stopped."
;;

*)
echo "Usage: $0 {start|stop}"
;;
esac



